version: '3.9'

networks:
  app-network:
    driver: bridge

services:
  traefik:
    image: traefik:v3
    container_name: spot_traefik
    restart: always
    environment:
      - DOCKER_API_VERSION=1.44
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/certs:/certs:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: spot_db
    restart: always
    networks:
      - app-network
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  backend:
    image: ghcr.io/night-pizza/spot/spot-backend:latest
    container_name: spot_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
      face_recognition:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${APP_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.backend.middlewares=strip-api"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.service=backend"
    env_file:
      - .env
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      WEBAUTHN_RP_ID: ${WEBAUTH_RP_ID}
      WEBAUTHN_RP_NAME: ${WEBAUTH_RP_NAME}
  
  frontend:
    image: ghcr.io/night-pizza/spot/spot-frontend:latest
    container_name: spot_frontend
    restart: always
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    networks:
      - app-network
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}
      
  face_recognition:
    image: ghcr.io/night-pizza/spot/spot-face_recognition:latest
    container_name: face_recognition_service
    restart: always
    networks:
      - app-network
    depends_on:
      - kafka
    volumes:
      - face_models:/root/.insightface
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_REQUEST_TOPIC: face.recognition.requests
      KAFKA_RESPONSE_TOPIC: system.events
      PYTHONUNBUFFERED: "1"

volumes:
  db_data:
  face_models:
