version: '3.9'
networks:
  app-network:
    driver: bridge

services:
  traefik:
      image: traefik:v3
      container_name: traefik
      environment:
      - DOCKER_API_VERSION=1.44
      extra_hosts:
        - "host.docker.internal:host-gateway"
      ports:
        - "80:80"
        - "443:443"
        - "8080:8080"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - ./traefik/certs:/certs:ro
        - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
        - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      restart: unless-stopped
      networks:
      - app-network
  backend:
    build: ./backend
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
      face_recognition:
        condition: service_started
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`${APP_HOST}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.service=backend"
      - "traefik.http.routers.backend.priority=90"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
      - "traefik.http.routers.backend.middlewares=api-ratelimit,strip-api"
      - "traefik.http.routers.backend-login.rule=Host(`${APP_HOST}`) && Path(`/api/user/login`)"
      - "traefik.http.routers.backend-login.entrypoints=websecure"
      - "traefik.http.routers.backend-login.tls=true"
      - "traefik.http.routers.backend-login.service=backend"
      - "traefik.http.routers.backend-login.priority=100"
      - "traefik.http.routers.backend-login.middlewares=login-ratelimit,strip-api"

      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.average=60"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.period=1m"
      - "traefik.http.middlewares.api-ratelimit.ratelimit.burst=20"
      - "traefik.http.middlewares.login-ratelimit.ratelimit.average=5"
      - "traefik.http.middlewares.login-ratelimit.ratelimit.period=1m"
      - "traefik.http.middlewares.login-ratelimit.ratelimit.burst=5"
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY: INFO
      LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB: INFO

  frontend:
    build: ./frontend
    depends_on:
      - backend
    networks:
      - app-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`${APP_HOST}`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.priority=10"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"

  postgres:
    image: postgres:16-alpine
    networks:
      - app-network
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-broker
    networks:
      - app-network
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: ${KAFKA_CLUSTER_ID}

  face_recognition:
    build: ./face_recognition
    container_name: face_recognition_service
    networks:
      - app-network
    depends_on:
      - kafka
    volumes:
      - face_models:/root/.insightface
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_REQUEST_TOPIC: face.recognition.requests
      KAFKA_RESPONSE_TOPIC: system.events
      PYTHONUNBUFFERED: "1"
volumes:
  postgres_data:
  face_models:
