spring.application.name=SPOT
spring.profiles.active=local
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.consumer.group-id=spot-group
kafka.topic.faceRecognitionRequests=face.recognition.requests
kafka.topic.systemEvents=system.events
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.threads.virtual.enabled=true
server.port=8080
springdoc.swagger-ui.path=/docs
server.forward-headers-strategy=framework
logging.level.org.springframework.security=DEBUG
server.servlet.session.cookie.secure=true 
server.servlet.session.cookie.http-only=true 
server.servlet.session.cookie.same-site=strict
server.servlet.session.timeout=10m
my-university.oauth.origin=${MY_UNIVERSITY_ORIGIN:}
my-university.oauth.client-id=${MY_UNIVERSITY_CLIENT_ID:}
my-university.oauth.client-secret=${MY_UNIVERSITY_CLIENT_SECRET:}
my-university.oauth.redirect-uri=${MY_UNIVERSITY_REDIRECT_URI:}
my-university.oauth.post-login-redirect-uri=${MY_UNIVERSITY_POST_LOGIN_REDIRECT_URI:/dashboard}
