import { createContext, useContext, useState, useEffect, type ReactNode } from 'react';
import { ConfigProvider, theme as antdTheme } from 'antd';
import enUS from 'antd/locale/en_US';
import ruRU from 'antd/locale/ru_RU';

type Theme = 'light' | 'dark';
type Language = 'en' | 'ru';

interface ThemeContextType {
    theme: Theme;
    toggleTheme: () => void;
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const ThemeContext = createContext<ThemeContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
    en: {
        dashboard: 'Dashboard',
        attendance: 'Attendance',
        sessions: 'Sessions',
        profile: 'Profile',
        logout: 'Logout',
        back: 'Back',
        add: 'Add',
        cancel: 'Cancel',
        submit: 'Submit',
        save: 'Save',
        edit: 'Edit',
        delete: 'Delete',
        close: 'Close',
        remove: 'Remove',
        ok: 'OK',
        continue: 'Continue',
        yes: 'Yes',
        no: 'No',
        name: 'Name',
        actions: 'Actions',
        login: 'Login',
        register: 'Register',
        password: 'Password',
        unavailable: 'Unavailable',
        retry: 'Retry',
        loading: 'Loading...',
        refresh: 'Refresh',
        create: 'Create',
        open: 'Open',
        view: 'View',
        export: 'Export',
        participants: 'Participants',
        owner: 'Owner',
        activeOnly: 'Active Only',
        completedOnly: 'Completed Only',
        newestFirst: 'Newest First',
        oldestFirst: 'Oldest First',
        searchSessions: 'Search sessions...',
        accountActions: 'Account actions',
        openNavigation: 'Open navigation',

        // Сессии
        clickToNameSession: 'Click to name the session',
        nameSessionBeforeEnd: 'Please name the session before ending it.',
        newSession: 'New Session',
        sessionDetails: 'Session Details',
        sessionCode: 'Session Code',
        geolocation: 'Geolocation',
        enabled: 'Enabled',
        disabled: 'Disabled',
        location: 'Location',
        active: 'Active',
        completed: 'Completed',
        sessionLive: 'Session live',
        noSessions: 'No sessions created yet',
        createFirstSession: 'Create your first session',
        manageSessions: 'Manage your attendance sessions',
        sessionTitle: 'Session Title',
        enableGeolocation: 'Enable Geolocation',
        allowedRadius: 'Allowed Radius',
        meters: 'meters',
        sessionCodeOptional: 'Session Code (optional)',
        sessionCodeHelp: 'Participants can use this code to join the session.',
        createSession: 'Create Session',
        sessionsCreated: 'Sessions Created',
        sessionsAttended: 'Sessions Attended',
        scannedStudents: 'Scanned Students',
        noAttendees: 'No attendees yet',
        addStudentManually: 'Add Student Manually',
        geolocationHelp: 'Students must be within this radius to mark attendance.',
        sessionId: 'Session ID',
        sessionIdRequired: 'Please enter a session ID.',
        sessionIdPositive: 'Session ID must be a positive integer.',
        sessionCodeRequired: 'Please enter a session code.',
        sessionMode: 'Session Mode',
        sessionModeRequired: 'Please choose a session mode.',
        qrCodeSession: 'QR Code session',
        codeWordSession: 'Code Word session',
        titleRequired: 'Please enter a session title.',
        titlePlaceholder: 'e.g. Machine Learning Lecture',
        pleaseSetLocation: 'Please set your location first.',
        sessionCreated: 'Session created successfully!',
        createFailed: 'Failed to create session',
        radiusRequired: 'Please enter an allowed radius.',
        radiusMin: 'Radius must be a positive number.',
        locationSet: 'Location set!',
        locationUpdated: 'Location updated!',
        locationPreview: 'Location preview',
        requireFaceRecognition: 'Require Face Recognition',
        faceRecognitionHelp: 'Students must scan their face to mark attendance.',
        codeExtra: 'Participants can use this code to join.',
        codePlaceholder: 'Enter password',
        validationMethods: 'Validation Methods',
        validationMethodsLabel: 'Validation Methods',
        passwordValidation: 'Password',
        faceRecognition: 'Face Recognition',
        none: 'None',
        ended: 'Ended',
        sessionFinished: 'Session finished',
        radius: 'Radius',
        addAttendee: 'Add attendee',
        endSession: 'End Session',
        endSessionQuestion: 'End session?',
        endSessionConfirm: 'Are you sure you want to end this session?',
        endSessionDescription: 'QR/code attendance will stop after ending the session. Participants will no longer be able to check in using this session.',
        checkedInUsersLoading: 'Loading checked-in users...',
        waitingQrToken: 'Waiting for backend QR token...',
        expandQr: 'Expand QR',
        expandMap: 'Expand Map',
        sessionEnded: 'Session ended',
        radiusUpdated: 'Radius updated',
        validRadiusRequired: 'Please enter a valid radius',
        validEmailRequired: 'Enter a valid email address.',
        innopolisEmailOnly: 'Only @innopolis.ru or @innopolis.university emails are allowed.',
        attendeeAdded: 'Attendee added.',
        attendeeRemoved: 'Attendee removed.',
        failedAddAttendee: 'Failed to add attendee.',
        failedRemoveAttendee: 'Failed to remove attendee.',
        failedLoadCheckedInUsers: 'Failed to load checked-in users.',
        failedLoadSessions: 'Failed to load sessions',
        failedEndSession: 'Failed to end session.',
        failedExportAttendance: 'Failed to export attendance.',
        exportedSuccessfully: 'Exported successfully',
        failedExport: 'Failed to export',
        standardCsv: 'Standard CSV',
        moodleCsv: 'Moodle CSV',
        plainText: 'Plain Text',
        sessionIdPositiveNumber: 'Session ID must be a positive number.',
        acquiringLocation: 'Acquiring location...',
        acquiringYourLocation: 'Acquiring your location...',
        adjustLocationHint: 'Drag the marker or click on the map to adjust the central location.',

        scanQR: 'Scan QR',
        scanQRCode: 'Scan QR Code',
        scanQRDesc: 'Use your camera to scan the session QR code',
        scanSessionQrDescription: 'Scan a session QR code to mark your attendance.',
        openCamera: 'Open Camera',
        enterSessionCode: 'Enter Session Code',
        enterCodeDesc: 'Enter the code shared for this session',
        submitCode: 'Submit Code',
        attendanceHistory: 'Attendance History',
        attendedSessions: 'Attended Sessions',
        sessionName: 'Session Name',
        date: 'Date',
        time: 'Time',
        noAttendanceRecords: 'No attendance records yet',
        noAttendedSessionsYet: 'No attended sessions yet',
        noAttendedSessionsDescription: 'You have not attended any sessions yet.',
        noSessionsMatchSearch: 'No sessions match your search criteria.',
        loadingAttendanceHistory: 'Loading attendance history...',
        markAttendance: 'Mark attendance',
        attended: 'Attended',
        attendanceSubmitted: 'Attendance submitted',
        qrAttendanceSubmitted: 'QR attendance submitted',
        attendanceSubmittedSuccess: 'Attendance submitted successfully!',
        submittingAttendance: 'Submitting attendance...',
        failedLoadAttendanceHistory: 'Failed to load attendance history',
        failedSubmitAttendance: 'Failed to submit attendance.',
        failedSubmitQrAttendance: 'Failed to submit QR attendance.',
        accessDenied: 'Access Denied',
        attendanceAccessDeniedDescription: 'Only students (SSO users) can mark their own attendance. You can only create sessions to collect attendance.',
        biometricDeviceRequired: 'Biometric Device Required',
        biometricDeviceRequiredDescription: 'You have not registered your biometric device yet. Please register your device to enable biometric verification.',
        biometricDeviceRequiredAttendanceDescription: 'You must register this device with your biometrics before you can mark attendance.',
        biometricVerificationRequired: 'Biometric Verification Required',
        biometricVerificationRequiredDescription: 'You skipped biometric verification at login. You must verify your identity to mark attendance.',
        registerDevice: 'Register Device',
        registerLater: 'Register Later',
        tryAgain: 'Try Again',
        verifyNow: 'Verify Now',
        verifyBiometrics: 'Verify Biometrics',
        verifyingBiometrics: 'Verifying...',
        biometricDeviceRegisteredSuccess: 'Biometric device registered successfully!',
        biometricRegistrationFailed: 'Biometric Registration Failed',
        biometricRegistrationRetry: '{error}. Would you like to try registering your device again or register it later?',
        biometricDeviceRegistrationFailed: 'Biometric device registration failed.',
        deviceAlreadyInUse: 'The device is already in use by someone else',
        identityVerifiedSuccess: 'Identity verified successfully!',
        biometricVerificationFailed: 'Biometric verification failed. Please try again.',
        biometricVerificationError: 'An error occurred during verification.',
        confirmIdentity: 'Confirm Identity',
        confirmIdentityDescription: 'Please confirm your identity using WebAuthn (Touch ID, Face ID or Windows Hello) to proceed.',
        skipForNow: 'Skip for now',
        failedDashboardStats: 'Failed to load dashboard statistics',
        startSession: 'Start a session',
        viewHistory: 'View History',
        reviewRecords: 'Review records',

        locationVerification: 'Location Verification',
        gettingLocation: 'Getting your location...',
        yourLocation: 'Your location',
        sessionLocation: 'Session location',
        withinAllowed: 'Within Allowed Area',
        outsideAllowed: 'Outside Allowed Area',
        distanceFromCenter: 'Distance from session center',
        proceedToSession: 'Proceed to Session',
        locationError: 'Unable to get location. Please enable GPS or disable geolocation.',
        locationPermissionError: 'Failed to get location. Please check browser permissions.',
        geolocationUnsupported: 'Geolocation is not supported by your browser.',
        getLocation: 'Get Location',
        locating: 'Locating...',
        locationAcquired: 'Location acquired!',
        viewGeolocationMap: 'View Geolocation Map',
        geolocationRequiredDescription: 'This session requires geolocation check-in. You must be inside the designated radius.',
        geolocationOptionalDescription: 'This session does not require geolocation check-in, but you can still view the session location.',
        geolocationCurrentOnlyDescription: 'You can check your current location here.',

        cameraPermissionDenied: 'Camera access was denied. Allow camera permission in your browser and try again.',
        noCameraFound: 'No camera was found on this device.',
        cameraInsecureContext: 'Camera scanning requires HTTPS or localhost. Open this site through HTTPS or localhost and try again.',
        cameraUnsupportedApi: 'This browser does not support the camera APIs required by this app.',
        cameraInitializationFailed: 'Could not start the QR scanner. Close the modal and try again.',
        qrReadFailed: 'Failed to read QR code from camera.',
        qrNoToken: 'QR code did not contain a token.',

        changePassword: 'Change Password',
        contactInformation: 'Contact Information',
        currentPassword: 'Current Password',
        newPassword: 'New Password',
        confirmPassword: 'Confirm Password',
        passwordMismatch: 'Passwords do not match',
        passwordChanged: 'Password changed successfully',
        passwordCurrentRequired: 'Please enter your current password',
        passwordNewRequired: 'Please enter a new password',
        passwordMinLength: 'Password must be at least 8 characters',
        passwordMinLengthLong: 'Password must be at least 8 characters long',
        passwordConfirmRequired: 'Please confirm your new password',
        changePasswordFailed: 'Failed to change password',
        updateFace: 'Update Face',
        updateFaceRecognition: 'Update Face Recognition',
        faceUpdated: 'Face updated successfully',
        webauthDeviceRegistered: 'WebAuth device key registered successfully!',
        webauthDeviceRegistrationFailed: 'WebAuth device key registration failed.',
        changeBiometricDevice: 'Change Biometric Device',
        registerBiometricDevice: 'Register Biometric Device',
        errorWhileLogout: 'Error while logout:',

        hello: 'Hello',
        quickActions: 'QUICK ACTIONS',
        viewAttendance: 'View Attendance',
        sessionNotFound: 'Session not found',
        goToSessions: 'Go to Sessions',
        loadingSession: 'Loading session...',
        sessionNotFoundError: 'Session not found. Please check the code.',

        emailRequired: 'Email cannot be empty',
        emailFormatInvalid: 'Email must be in lowercase and contain no spaces',
        emailDomainInvalid: 'Email must belong to @innopolis.ru or @innopolis.university',
        innopolisSsoRequired: 'Innopolis emails must use SSO to log in or register',
        continueWithMyUniversity: 'Continue with My.University',
        passwordRequired: 'Password cannot be empty',
        passwordDigitRequired: 'Password must contain at least one digit',
        passwordLowerRequired: 'Password must contain at least one lowercase letter',
        passwordUpperRequired: 'Password must contain at least one uppercase letter',
        passwordSpecialRequired: 'Password must contain at least one special character',
        loginFailed: 'Login failed',
        registrationFailed: 'Registration failed',

        faceRegistrationRequired: 'Face Registration Required',
        faceRegistrationRequiredDescription: 'You have not registered your face yet. Please register your face to enable face recognition check-in.',
        registerFace: 'Register Face',
        faceRegistration: 'Face Registration',
        faceRegistrationIntro: 'Before you start using SPOT, please complete the required face scan. The camera will start automatically after liveness verification.',
        faceVerified: 'Face Verified!',
        faceVerificationFailed: 'Face Verification Failed',
        faceRegisteredSuccess: 'Your face has been successfully registered.',
        faceRetryHint: 'Please try again or ensure good lighting.',
        retakePhotos: 'Retake Photos',
        loadingLivenessModel: 'Loading liveness detection model...',
        livenessModelFailed: 'Failed to load liveness detection model.',
        lookAtCameraMouthClosed: 'Please look at the camera with mouth closed',
        openYourMouth: 'Now open your mouth!',
        livenessVerified: 'Liveness Verified!',
        livenessFailed: 'Liveness Verification Failed',
        retryingInSeconds: 'Please try again. Retrying in {seconds} seconds...',
        capturingPhoto: 'Capturing photo...',
        capturingPhotoOf: 'Capturing photo {current} of {total}...',
        nextPhotoInSeconds: 'Next photo in 3 seconds... ({current} of {total})',
        submittingToServer: 'Submitting to server...',
        capturingPhotos: 'Capturing photos...',
        sendingVerificationRequest: 'Sending verification request...',
        processing: 'Processing...',
        failedCapturePhotos: 'Failed to capture photos.',
        faceVerificationRequired: 'Face Verification Required',
        verifyingFace: 'Verifying Face...',
        verifyingFaceDescription: 'We are extracting your face embedding and validating attendance. Please wait.',
        faceAttendanceSuccess: 'Your face was successfully matched and attendance registered.',
        faceNotRecognized: 'Face not recognized.',
        noRequestIdReturned: 'No request ID returned from backend.',
        faceRegistrationTimedOut: 'Face registration timed out.',
        noVerificationRequestId: 'No verification request ID returned from server.',
        verificationTimedOut: 'Verification request timed out.',
        faceValidationFailed: 'Face validation failed',
    },
    ru: {
        dashboard: 'Панель',
        attendance: 'Посещаемость',
        sessions: 'Сессии',
        profile: 'Профиль',
        logout: 'Выйти',
        back: 'Назад',
        add: 'Добавить',
        cancel: 'Отмена',
        submit: 'Отправить',
        save: 'Сохранить',
        edit: 'Изменить',
        delete: 'Удалить',
        close: 'Закрыть',
        remove: 'Удалить',
        ok: 'ОК',
        continue: 'Продолжить',
        yes: 'Да',
        no: 'Нет',
        name: 'Имя',
        actions: 'Действия',
        login: 'Войти',
        register: 'Зарегистрироваться',
        password: 'Пароль',
        unavailable: 'Недоступно',
        retry: 'Повторить',
        loading: 'Загрузка...',
        refresh: 'Обновить',
        create: 'Создать',
        open: 'Открыть',
        view: 'Просмотр',
        export: 'Экспорт',
        participants: 'Участники',
        owner: 'Владелец',
        activeOnly: 'Только активные',
        completedOnly: 'Только завершённые',
        newestFirst: 'Сначала новые',
        oldestFirst: 'Сначала старые',
        searchSessions: 'Поиск сессий...',
        accountActions: 'Действия с аккаунтом',
        openNavigation: 'Открыть навигацию',

        newSession: 'Новая сессия',
        sessionDetails: 'Детали сессии',
        sessionCode: 'Код сессии',
        geolocation: 'Геолокация',
        enabled: 'Включена',
        disabled: 'Отключена',
        location: 'Местоположение',
        active: 'Активна',
        completed: 'Завершена',
        sessionLive: 'Сессия активна',
        noSessions: 'Сессии ещё не созданы',
        createFirstSession: 'Создайте первую сессию',
        manageSessions: 'Управляйте сессиями посещаемости',
        sessionTitle: 'Название сессии',
        enableGeolocation: 'Включить геолокацию',
        allowedRadius: 'Разрешённый радиус',
        meters: 'метров',
        sessionCodeOptional: 'Код сессии (необязательно)',
        sessionCodeHelp: 'Участники смогут использовать этот код для входа в сессию.',
        createSession: 'Создать сессию',
        sessionsCreated: 'Создано сессий',
        sessionsAttended: 'Посещено сессий',
        scannedStudents: 'Отмеченные студенты',
        noAttendees: 'Участников пока нет',
        addStudentManually: 'Добавить студента вручную',
        geolocationHelp: 'Студенты должны находиться в этом радиусе, чтобы отметиться.',
        sessionId: 'ID сессии',
        sessionIdRequired: 'Введите ID сессии.',
        sessionIdPositive: 'ID сессии должен быть положительным целым числом.',
        sessionCodeRequired: 'Введите код сессии.',
        sessionMode: 'Режим сессии',
        sessionModeRequired: 'Выберите режим сессии.',
        qrCodeSession: 'Сессия с QR-кодом',
        codeWordSession: 'Сессия с кодовым словом',
        titleRequired: 'Введите название сессии.',
        titlePlaceholder: 'например, лекция по машинному обучению',
        pleaseSetLocation: 'Сначала укажите местоположение.',
        sessionCreated: 'Сессия успешно создана!',
        createFailed: 'Не удалось создать сессию',
        radiusRequired: 'Введите разрешённый радиус.',
        radiusMin: 'Радиус должен быть положительным числом.',
        locationSet: 'Местоположение задано!',
        locationUpdated: 'Местоположение обновлено!',
        locationPreview: 'Предпросмотр местоположения',
        requireFaceRecognition: 'Требовать распознавание лица',
        faceRecognitionHelp: 'Студенты должны просканировать лицо, чтобы отметиться.',
        codeExtra: 'Участники смогут использовать этот код для входа.',
        codePlaceholder: 'Введите пароль',
        validationMethods: 'Методы проверки',
        validationMethodsLabel: 'Методы проверки',
        passwordValidation: 'Пароль',
        faceRecognition: 'Распознавание лица',
        none: 'Нет',
        ended: 'Завершена',
        sessionFinished: 'Сессия завершена',
        radius: 'Радиус',
        addAttendee: 'Добавить участника',
        endSession: 'Завершить сессию',
        endSessionQuestion: 'Завершить сессию?',
        endSessionConfirm: 'Вы уверены, что хотите завершить эту сессию?',
        endSessionDescription: 'После завершения сессии отметка по QR/коду остановится. Участники больше не смогут отметиться в этой сессии.',
        checkedInUsersLoading: 'Загрузка отметившихся пользователей...',
        waitingQrToken: 'Ожидание QR-токена от сервера...',
        expandQr: 'Развернуть QR',
        expandMap: 'Развернуть карту',
        sessionEnded: 'Сессия завершена',
        radiusUpdated: 'Радиус обновлён',
        validRadiusRequired: 'Введите корректный радиус',
        validEmailRequired: 'Введите корректный email.',
        innopolisEmailOnly: 'Разрешены только email @innopolis.ru или @innopolis.university.',
        attendeeAdded: 'Участник добавлен.',
        attendeeRemoved: 'Участник удалён.',
        failedAddAttendee: 'Не удалось добавить участника.',
        failedRemoveAttendee: 'Не удалось удалить участника.',
        failedLoadCheckedInUsers: 'Не удалось загрузить отметившихся пользователей.',
        failedLoadSessions: 'Не удалось загрузить сессии',
        failedEndSession: 'Не удалось завершить сессию.',
        failedExportAttendance: 'Не удалось экспортировать посещаемость.',
        exportedSuccessfully: 'Экспорт выполнен',
        failedExport: 'Не удалось экспортировать',
        standardCsv: 'Стандартный CSV',
        moodleCsv: 'Moodle CSV',
        plainText: 'Обычный текст',
        sessionIdPositiveNumber: 'ID сессии должен быть положительным числом.',
        acquiringLocation: 'Определяем местоположение...',
        acquiringYourLocation: 'Определяем ваше местоположение...',
        adjustLocationHint: 'Перетащите маркер или нажмите на карту, чтобы изменить центр.',

        scanQR: 'Сканировать QR',
        scanQRCode: 'Сканировать QR-код',
        scanQRDesc: 'Используйте камеру для сканирования QR-кода сессии',
        scanSessionQrDescription: 'Отсканируйте QR-код сессии, чтобы отметиться.',
        openCamera: 'Открыть камеру',
        enterSessionCode: 'Ввести код сессии',
        enterCodeDesc: 'Введите код, выданный для этой сессии',
        submitCode: 'Отправить код',
        attendanceHistory: 'История посещаемости',
        attendedSessions: 'Посещённые сессии',
        sessionName: 'Название сессии',
        date: 'Дата',
        time: 'Время',
        noAttendanceRecords: 'Записей о посещаемости пока нет',
        noAttendedSessionsYet: 'Посещённых сессий пока нет',
        noAttendedSessionsDescription: 'Вы ещё не посещали ни одной сессии.',
        noSessionsMatchSearch: 'Нет сессий, подходящих под фильтры.',
        loadingAttendanceHistory: 'Загрузка истории посещаемости...',
        markAttendance: 'Отметиться',
        attended: 'Посещено',
        attendanceSubmitted: 'Посещаемость отмечена',
        qrAttendanceSubmitted: 'Посещаемость по QR отмечена',
        attendanceSubmittedSuccess: 'Посещаемость успешно отмечена!',
        submittingAttendance: 'Отправка отметки...',
        failedLoadAttendanceHistory: 'Не удалось загрузить историю посещаемости',
        failedSubmitAttendance: 'Не удалось отправить посещаемость.',
        failedSubmitQrAttendance: 'Не удалось отправить посещаемость по QR.',
        accessDenied: 'Доступ запрещён',
        attendanceAccessDeniedDescription: 'Только студенты (SSO-пользователи) могут отмечать собственную посещаемость. Вы можете создавать сессии для сбора посещаемости.',
        biometricDeviceRequired: 'Требуется биометрическое устройство',
        biometricDeviceRequiredDescription: 'Вы ещё не зарегистрировали биометрическое устройство. Зарегистрируйте его, чтобы включить биометрическую проверку.',
        biometricDeviceRequiredAttendanceDescription: 'Чтобы отметиться, нужно зарегистрировать это устройство для биометрической проверки.',
        biometricVerificationRequired: 'Требуется биометрическая проверка',
        biometricVerificationRequiredDescription: 'Вы пропустили биометрическую проверку при входе. Подтвердите личность, чтобы отметиться.',
        registerDevice: 'Зарегистрировать устройство',
        registerLater: 'Позже',
        tryAgain: 'Попробовать снова',
        verifyNow: 'Проверить сейчас',
        verifyBiometrics: 'Проверить биометрию',
        verifyingBiometrics: 'Проверка...',
        biometricDeviceRegisteredSuccess: 'Биометрическое устройство зарегистрировано!',
        biometricRegistrationFailed: 'Не удалось зарегистрировать биометрию',
        biometricRegistrationRetry: '{error}. Хотите попробовать зарегистрировать устройство ещё раз или сделать это позже?',
        biometricDeviceRegistrationFailed: 'Не удалось зарегистрировать биометрическое устройство.',
        deviceAlreadyInUse: 'Это устройство уже используется другим пользователем',
        identityVerifiedSuccess: 'Личность подтверждена!',
        biometricVerificationFailed: 'Биометрическая проверка не пройдена. Попробуйте ещё раз.',
        biometricVerificationError: 'Во время проверки произошла ошибка.',
        confirmIdentity: 'Подтвердите личность',
        confirmIdentityDescription: 'Подтвердите личность через WebAuthn (Touch ID, Face ID или Windows Hello), чтобы продолжить.',
        skipForNow: 'Пропустить сейчас',
        failedDashboardStats: 'Не удалось загрузить статистику панели',
        startSession: 'Начать сессию',
        viewHistory: 'История',
        reviewRecords: 'Просмотреть записи',

        locationVerification: 'Проверка местоположения',
        gettingLocation: 'Определяем ваше местоположение...',
        yourLocation: 'Ваше местоположение',
        sessionLocation: 'Местоположение сессии',
        withinAllowed: 'В разрешённой зоне',
        outsideAllowed: 'Вне разрешённой зоны',
        distanceFromCenter: 'Расстояние от центра сессии',
        proceedToSession: 'Перейти к сессии',
        locationError: 'Не удалось определить местоположение. Включите GPS или отключите геолокацию.',
        locationPermissionError: 'Не удалось получить местоположение. Проверьте разрешения браузера.',
        geolocationUnsupported: 'Ваш браузер не поддерживает геолокацию.',
        getLocation: 'Получить геолокацию',
        locating: 'Определяем...',
        locationAcquired: 'Геолокация получена!',
        viewGeolocationMap: 'Показать карту геолокации',
        geolocationRequiredDescription: 'Эта сессия требует отметку по геолокации. Вы должны находиться внутри заданного радиуса.',
        geolocationOptionalDescription: 'Эта сессия не требует отметку по геолокации, но вы всё равно можете посмотреть место сессии.',
        geolocationCurrentOnlyDescription: 'Здесь можно проверить ваше текущее местоположение.',

        cameraPermissionDenied: 'Доступ к камере запрещён. Разрешите камеру в браузере и попробуйте снова.',
        noCameraFound: 'На этом устройстве камера не найдена.',
        cameraInsecureContext: 'Сканирование камерой требует HTTPS или localhost. Откройте сайт через HTTPS или localhost и попробуйте снова.',
        cameraUnsupportedApi: 'Этот браузер не поддерживает API камеры, нужные приложению.',
        cameraInitializationFailed: 'Не удалось запустить QR-сканер. Закройте окно и попробуйте снова.',
        qrReadFailed: 'Не удалось прочитать QR-код с камеры.',
        qrNoToken: 'QR-код не содержит токен.',

        changePassword: 'Сменить пароль',
        contactInformation: 'Контактная информация',
        currentPassword: 'Текущий пароль',
        newPassword: 'Новый пароль',
        confirmPassword: 'Подтвердите пароль',
        passwordMismatch: 'Пароли не совпадают',
        passwordChanged: 'Пароль успешно изменён',
        passwordCurrentRequired: 'Введите текущий пароль',
        passwordNewRequired: 'Введите новый пароль',
        passwordMinLength: 'Пароль должен быть не короче 8 символов',
        passwordMinLengthLong: 'Пароль должен быть не короче 8 символов',
        passwordConfirmRequired: 'Подтвердите новый пароль',
        changePasswordFailed: 'Не удалось изменить пароль',
        updateFace: 'Обновить лицо',
        updateFaceRecognition: 'Обновить распознавание лица',
        faceUpdated: 'Лицо успешно обновлено',
        webauthDeviceRegistered: 'Ключ устройства WebAuth успешно зарегистрирован!',
        webauthDeviceRegistrationFailed: 'Не удалось зарегистрировать ключ устройства WebAuth.',
        changeBiometricDevice: 'Сменить биометрическое устройство',
        registerBiometricDevice: 'Зарегистрировать биометрическое устройство',
        errorWhileLogout: 'Ошибка при выходе:',

        hello: 'Здравствуйте',
        quickActions: 'БЫСТРЫЕ ДЕЙСТВИЯ',
        viewAttendance: 'Просмотр посещаемости',
        sessionNotFound: 'Сессия не найдена',
        goToSessions: 'Перейти к сессиям',
        loadingSession: 'Загрузка сессии...',
        sessionNotFoundError: 'Сессия не найдена. Проверьте код.',

        emailRequired: 'Email не может быть пустым',
        emailFormatInvalid: 'Email должен быть в нижнем регистре и без пробелов',
        emailDomainInvalid: 'Email должен относиться к @innopolis.ru или @innopolis.university',
        innopolisSsoRequired: 'Для email Innopolis нужно входить или регистрироваться через SSO',
        continueWithMyUniversity: 'Продолжить через My.University',
        passwordRequired: 'Пароль не может быть пустым',
        passwordDigitRequired: 'Пароль должен содержать хотя бы одну цифру',
        passwordLowerRequired: 'Пароль должен содержать хотя бы одну строчную букву',
        passwordUpperRequired: 'Пароль должен содержать хотя бы одну заглавную букву',
        passwordSpecialRequired: 'Пароль должен содержать хотя бы один специальный символ',
        loginFailed: 'Не удалось войти',
        registrationFailed: 'Не удалось зарегистрироваться',

        faceRegistrationRequired: 'Требуется регистрация лица',
        faceRegistrationRequiredDescription: 'Вы ещё не зарегистрировали лицо. Зарегистрируйте его, чтобы использовать отметку по распознаванию лица.',
        registerFace: 'Зарегистрировать лицо',
        faceRegistration: 'Регистрация лица',
        faceRegistrationIntro: 'Перед началом работы в SPOT пройдите сканирование лица. Камера запустится автоматически после проверки живости.',
        faceVerified: 'Лицо подтверждено!',
        faceVerificationFailed: 'Проверка лица не пройдена',
        faceRegisteredSuccess: 'Ваше лицо успешно зарегистрировано.',
        faceRetryHint: 'Попробуйте ещё раз или проверьте освещение.',
        retakePhotos: 'Переснять фото',
        loadingLivenessModel: 'Загрузка модели проверки живости...',
        livenessModelFailed: 'Не удалось загрузить модель проверки живости.',
        lookAtCameraMouthClosed: 'Посмотрите в камеру с закрытым ртом',
        openYourMouth: 'Теперь откройте рот!',
        livenessVerified: 'Живость подтверждена!',
        livenessFailed: 'Проверка живости не пройдена',
        retryingInSeconds: 'Попробуйте ещё раз. Повтор через {seconds} сек.',
        capturingPhoto: 'Снимаем фото...',
        capturingPhotoOf: 'Снимаем фото {current} из {total}...',
        nextPhotoInSeconds: 'Следующее фото через 3 секунды... ({current} из {total})',
        submittingToServer: 'Отправка на сервер...',
        capturingPhotos: 'Снимаем фото...',
        sendingVerificationRequest: 'Отправка запроса на проверку...',
        processing: 'Обработка...',
        failedCapturePhotos: 'Не удалось сделать фото.',
        faceVerificationRequired: 'Требуется проверка лица',
        verifyingFace: 'Проверяем лицо...',
        verifyingFaceDescription: 'Мы извлекаем embedding лица и подтверждаем посещаемость. Пожалуйста, подождите.',
        faceAttendanceSuccess: 'Лицо успешно сопоставлено, посещаемость отмечена.',
        faceNotRecognized: 'Лицо не распознано.',
        noRequestIdReturned: 'Сервер не вернул ID запроса.',
        faceRegistrationTimedOut: 'Время регистрации лица истекло.',
        noVerificationRequestId: 'Сервер не вернул ID запроса проверки.',
        verificationTimedOut: 'Время проверки истекло.',
        faceValidationFailed: 'Проверка лица не пройдена',
    },
};

export const ThemeProvider = ({ children }: { children: ReactNode }) => {
    const [theme, setTheme] = useState<Theme>(() => {
        const stored = localStorage.getItem('theme') as Theme | null;
        return stored || 'light';
    });
    const [language, setLanguage] = useState<Language>(() => {
        const stored = localStorage.getItem('language') as Language | null;
        return stored || 'en';
    });

    useEffect(() => {
        localStorage.setItem('theme', theme);
        document.documentElement.setAttribute('data-theme', theme);
    }, [theme]);

    useEffect(() => {
        localStorage.setItem('language', language);
        document.documentElement.lang = language;
    }, [language]);

    const toggleTheme = () => {
        setTheme((prev) => (prev === 'light' ? 'dark' : 'light'));
    };

    const t = (key: string): string => {
        return translations[language]?.[key] || translations.en[key] || key;
    };

    return (
        <ThemeContext.Provider value={{ theme, toggleTheme, language, setLanguage, t }}>
            <ConfigProvider
                locale={language === 'ru' ? ruRU : enUS}
                theme={{
                    algorithm: theme === 'dark' ? antdTheme.darkAlgorithm : antdTheme.defaultAlgorithm,
                    token: {
                        colorPrimary: '#5ec832',
                        ...(theme === 'dark' ? {
                            colorBgBase: '#0f172a',
                            colorBgElevated: '#1e293b',
                            colorTextBase: '#f1f5f9',
                            colorBorder: '#334155',
                            colorBgContainer: '#2d3748',
                        } : {})
                    }
                }}
            >
                {children}
            </ConfigProvider>
        </ThemeContext.Provider>
    );
};

export const useTheme = () => {
    const ctx = useContext(ThemeContext);
    if (!ctx) throw new Error('useTheme must be used within ThemeProvider');
    return ctx;
};
